# Generated by Django 5.2.8 on 2025-12-22 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='تیتر')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت پست')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین زمان تغییرات پست')),
                ('visible', models.BooleanField(default=False, verbose_name='قابل رویت بودن')),
                ('show_to', models.CharField(choices=[('nobody', 'هیچکس'), ('closefriends', 'دوستان صمیمی'), ('all', 'همه')], default='nobody', max_length=20, verbose_name='مشاهده به')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('category', models.CharField(choices=[('social', 'اجتماعی'), ('sport', 'ورزشی')], max_length=20, verbose_name='دسته بندی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_pictures/20251222', verbose_name='اپلود عکس')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست',
            },
        ),
    ]
