# Generated by Django 5.2.8 on 2025-11-19 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_category_alter_post_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('social', 'اجتماعی'), ('sport', 'ورزشی')], max_length=20, verbose_name='دسته یندی'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت پست'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف شده'),
        ),
        migrations.AlterField(
            model_name='post',
            name='show_to',
            field=models.CharField(choices=[('nobody', 'هیچکس'), ('closefriends', 'دوستان صمیمی'), ('all', 'همه')], default='nobody', max_length=20, verbose_name='مشاهده به'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, verbose_name='تیتر'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین زمان تغییرات پست'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user', verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='post',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='قابل رویت بودن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(null=True, verbose_name='درباره من'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(choices=[('tehran', 'تهران'), ('isfahan', 'اصهان')], default='isfahan', max_length=20, verbose_name='شهر محل زندگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='close_friend',
            field=models.ManyToManyField(blank=True, null=True, to='core.user', verbose_name='دوستان نزدیک'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, verbose_name='رمز ورود'),
        ),
    ]
