# Generated by Django 5.2.8 on 2025-12-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_category_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_pictures'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('social', 'اجتماعی'), ('sport', 'ورزشی')], max_length=20, verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='درباره من'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(choices=[('tehran', 'تهران'), ('isfahan', 'اصفهان')], default='isfahan', max_length=20, verbose_name='شهر محل زندگی'),
        ),
    ]
